### ISSUE TITLE
Update next redux wrapper to 6.0 to remove Provider in App component

### ISSUE THREAD

**Issue by cristian05** [pankod/next-boilerplate#102]
https://github.com/pankod/next-boilerplate/blob/56f958798671ebce1d6615dedc924dafbf4d0b8c/pages/_app/index.tsx#L34

With [6.0 version of next redux wrapper](https://github.com/kirill-konshin/next-redux-wrapper/releases)  `App` should no longer wrap its children with `Provider`, it is now done internally.

**Comment by vitaliemiron** [comment]
I am not sure, but with this [feature](https://github.com/pankod/next-boilerplate/issues/96)  redux shoul be replaced with apollo.

**Comment by cristian05** [comment]
Why are you considering replacing redux with apollo? Can you give me some reason to make that decision. 

Because I believe that redux is and will be a better choice for large scale projects:
[This](https://www.youtube.com/watch?v=zhmIox9iZ9A ) is the resume...

**Comment by vitaliemiron** [comment]
@cristian05 This video was recorded in 2018, so may be you should try use GraphQL now.
In my opinion it is better for large scale projects because you can get data that you want, you can use same endpoint for an Android app and IOS so this is very important to not build 100 of endpoints, just one.

**Comment by BatuhanW** [comment]
Hi @cristian05, I'll be handling this issue, thanks for the report!

**Comment by omeraplak** [comment]
@cristian05 Hi,

It has been a long time since we started next-boilerplate project. We are proud that it helped many frontend developers around the globe to speed up their frontend development cycles.

In time, we took valuable lessons from our experience and the community feedback:

- There are infinite number of frontend technologies and it's impossible to combine everything in a single boilerplate product.
- The project is hard to maintain with tons of external dependencies.
To tackle the complexity problem we started a new project from scratch. We call it "superplate" - the frontend boilerplate with superpowers.

It's built on top of a plugin architecture and allows you integrate your own tools and best practices with ease. It also includes more than 30 built-in plugins of your favorite tools.

superplate's default framework is Next.js, so you can start using it immediately instead of next-boilerplate. More framework targets are coming soon.

You may checkout the project from the [repo page](https://github.com/pankod/superplate) or [documentation](https://pankod.github.io/superplate/).
