### ISSUE TITLE
How to deploy to vercel?

### ISSUE THREAD

**Issue by waltermvp** [pankod/next-boilerplate#117]
Any guidelines on how to deploy to vercel since they no longer support docker?

**Comment by BatuhanW** [comment]
Hi @waltermvp Thanks for the issue, we are working on updating repository to use latest version and make all dependencies compatible. Then you'll be able to deploy to vercel. Please watch the repository for the updates, also all contributions are welcome 🙌

**Comment by Arunkumar-MS** [comment]
@BatuhanW Any updates on this?

**Comment by Vadorequest** [comment]
This isn't a direct solution (I'm not familiar with Pankod boilerplate yet), but I'm authoring another Next.js boilerplate which has full Vercel support. 

I've got no idea on how complicated it might be to migrate, but hopefully this might help you. 

https://github.com/UnlyEd/next-right-now

**Comment by omeraplak** [comment]
@cristian05 @Arunkumar-MS  Hi,

It has been a long time since we started next-boilerplate project. We are proud that it helped many frontend developers around the globe to speed up their frontend development cycles.

In time, we took valuable lessons from our experience and the community feedback:

- There are infinite number of frontend technologies and it's impossible to combine everything in a single boilerplate product.
- The project is hard to maintain with tons of external dependencies.
To tackle the complexity problem we started a new project from scratch. We call it "superplate" - the frontend boilerplate with superpowers.

It's built on top of a plugin architecture and allows you integrate your own tools and best practices with ease. It also includes more than 30 built-in plugins of your favorite tools.

superplate's default framework is Next.js, so you can start using it immediately instead of next-boilerplate. More framework targets are coming soon.

You may checkout the project from the [repo page](https://github.com/pankod/superplate) or [documentation](https://pankod.github.io/superplate/).

**Comment by Arunkumar-MS** [comment]
@omeraplak thanks for your reply. We have made the necessary changes to our codebase to migrate to vercel and Now we are up to date with nextjs version and our project runs on vercel now. 

Thanks for all the hard work you guys put in for creating this boilerplate :)
