### ISSUE TITLE
HMR for styled child components not working

### ISSUE THREAD

**Issue by TotallWAR** [pankod/next-boilerplate#126]
Hi!
Perfect starter, i like it very much!

I found a bug with HMR for child styled components.
For example if you modify shared Button component's styles in `Basic/Button/index.tsx` it is not reloaded, after page reload styles are not applied too. So there is only one solution - rebuild project and start dev again.

**Comment by omeraplak** [comment]
@TotallWAR  Hi,

It has been a long time since we started next-boilerplate project. We are proud that it helped many frontend developers around the globe to speed up their frontend development cycles.

In time, we took valuable lessons from our experience and the community feedback:

- There are infinite number of frontend technologies and it's impossible to combine everything in a single boilerplate product.
- The project is hard to maintain with tons of external dependencies.
To tackle the complexity problem we started a new project from scratch. We call it "superplate" - the frontend boilerplate with superpowers.

It's built on top of a plugin architecture and allows you integrate your own tools and best practices with ease. It also includes more than 30 built-in plugins of your favorite tools.

superplate's default framework is Next.js, so you can start using it immediately instead of next-boilerplate. More framework targets are coming soon.

You may checkout the project from the [repo page](https://github.com/pankod/superplate) or [documentation](https://pankod.github.io/superplate/).
