### ISSUE TITLE
NPM audit

### ISSUE THREAD

**Issue by LemonJuicer** [pankod/next-boilerplate#128]
I just runned
`npm install`
and audit gave me this:
`
found 4083 vulnerabilities (4070 low, 1 moderate, 12 high)
  run `npm audit fix` to fix them, or `npm audit` for details
`
I think this is a little bit too many

**Comment by Vadorequest** [comment]
Unrelated to Pankod, but the [Next Right Now](https://github.com/UnlyEd/next-right-now) boilerplate has similar stats:

```
2924 vulnerabilities found - Packages audited: 2651
Severity: 2914 Low | 10 High
```

And the severity really depends on how your project is being used, if you generate static pages then no matter how many vulnerabilities, as they cannot be exploited outside your localhost environment.

I wouldn't stress too much over this, it's really time-consuming for and not often worth it, unless you find a vulnerability that can be exploited in real conditions.

**Comment by omeraplak** [comment]
@LemonJuicer  Hi,

It has been a long time since we started next-boilerplate project. We are proud that it helped many frontend developers around the globe to speed up their frontend development cycles.

In time, we took valuable lessons from our experience and the community feedback:

- There are infinite number of frontend technologies and it's impossible to combine everything in a single boilerplate product.
- The project is hard to maintain with tons of external dependencies.
To tackle the complexity problem we started a new project from scratch. We call it "superplate" - the frontend boilerplate with superpowers.

It's built on top of a plugin architecture and allows you integrate your own tools and best practices with ease. It also includes more than 30 built-in plugins of your favorite tools.

superplate's default framework is Next.js, so you can start using it immediately instead of next-boilerplate. More framework targets are coming soon.

You may checkout the project from the [repo page](https://github.com/pankod/superplate) or [documentation](https://pankod.github.io/superplate/).
