### ISSUE TITLE
Typescript & Babel

### ISSUE THREAD

**Issue by gerardolima** [pankod/next-boilerplate#2]
For me it sounds confusing using Babel on a typescript codebase (i.e both add js shims into the generated code).

Could you please tell why you made this choice? What benefits does Babel add for typescript development?

Please don't see it as a criticism, I'm genuinely curious about this.

**Comment by andre-araujo** [comment]
Hi @gerardolima, babel is already used as a transpiler in nextjs, also I found a nice article showing some benefits of using TypeScript with Babel here: https://iamturns.com/typescript-babel/

**Comment by omeraplak** [comment]
Hi @gerardolima ,
Babel is great tool for compiling javascript.I understand why you’re confused like “why do i use babel with typescript?” Because i also have these kinds of confusions but i have great answers for them. 

- You can easy manage pollyfill with Babel. (https://babeljs.io/docs/en/babel-preset-env)
- You can use babel plugins (https://babeljs.io/docs/en/plugins)
- You can take part in the robust babel ecosystem (typechecking, error checking etc...)

Also you can read more,
[https://dev.to/saltyshiomix/why-babel-with-typescript-56l5](url)
[https://blogs.msdn.microsoft.com/typescript/2018/08/27/typescript-and-babel-7/](url)
[http://artsy.github.io/blog/2017/11/27/Babel-7-and-TypeScript/](url)

**Comment by gerardolima** [comment]
hey, @omeraplak, Typescript also injects polyfills, introduces its runtime, including module handling,  and produces code targeted to specific ECMA Script versions; how those relate to Babel ones? About type checking, I really can't see any improvement Babel can bring over TypeScript ... but anyway, thank you for your thoughts and for the articles
