### ISSUE TITLE
Dependency cycle detected 

### ISSUE THREAD

**Issue by cristian05** [pankod/next-boilerplate#81]
There is an import dependencie cycle between:

`src/Interfaces/index.ts`:
    `export * from '@Redux/IStore';`

and

`src/Redux/IStore.d.ts`:
`import { IHomePage } from '@Interfaces';`

Eslint rule that detect the issue: 
https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-cycle.md

**Comment by futuredayv** [comment]
Hi @cristian05!

Thanks for pointing out that. It will be resolved in next PR ⏳.

**Comment by omeraplak** [comment]
@cristian05 Hi,

It has been a long time since we started next-boilerplate project. We are proud that it helped many frontend developers around the globe to speed up their frontend development cycles.

In time, we took valuable lessons from our experience and the community feedback:

- There are infinite number of frontend technologies and it's impossible to combine everything in a single boilerplate product.
- The project is hard to maintain with tons of external dependencies.
To tackle the complexity problem we started a new project from scratch. We call it "superplate" - the frontend boilerplate with superpowers.

It's built on top of a plugin architecture and allows you integrate your own tools and best practices with ease. It also includes more than 30 built-in plugins of your favorite tools.

superplate's default framework is Next.js, so you can start using it immediately instead of next-boilerplate. More framework targets are coming soon.

You may checkout the project from the [repo page](https://github.com/pankod/superplate) or [documentation](https://pankod.github.io/superplate/).
