### ISSUE TITLE
Can I import this boilerplate directly to CodeSandBox.io?

### ISSUE THREAD

**Issue by karka86** [pankod/next-boilerplate#85]
When I tried this, it got the below error through 
__https://codesandbox.io/s/pensive-river-id3ch__

```js
$ cross-env NODE_ENV=production node dist/index.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/sandbox/dist/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.21.1
```

**Comment by futuredayv** [comment]
Hi @karka86!

__Codesandbox__ automatically tries to `yarn start`, and in our `package.json` you need to build the project beforehand to be able to call start. As the error message says, `/dist` is NOT present. This is because you haven't build the project yet.

You can fork and run `npm run start:dev` in terminal to start hacking.

[Eventually, I already run that if you're still interesting 🎉](https://codesandbox.io/s/next-boilerplate-jumpstart-gc4fd)
