### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by vitaliemiron** [pankod/next-boilerplate#96]
Your boilerplate is really nice, i love it.
It is possible to add option to replace redux with GraphQL?

**Comment by omeraplak** [comment]
Hi @vitaliemiron ,
Thanks for reaching us. We have added this feature to our backlog. We’ll update it soon.

**Comment by maihungdev** [comment]
> Hi @vitaliemiron ,
> Thanks for reaching us. We have added this feature to our backlog. We’ll update it soon.

**I think this feature is necessary, can you update soon?**

**Comment by Vadorequest** [comment]
I'm building NRN, which is similar to Next Boilerplate (it's another boilerplate). GraphQL is supported by default there since the beginning (using GraphCMS vendor).

I'm currently working on the v2, which features latest Next.js SSG support `getStaticProps`, WIP at https://github.com/UnlyEd/next-right-now/pull/52

You can take a look at the PR branch to see how I implemented GraphQL support. Also, https://unlyed.github.io/next-right-now/ is the general documentation.

Live demo at https://v1-hyb-mst-aptd-gcms-lcz-sty.now.sh/

**Comment by Vadorequest** [comment]
Until it's officially supported, you might learn a few things by looking at the [Next Right Now](https://github.com/UnlyEd/next-right-now) boilerplate, most especially the [GraphCMS preset](https://github.com/UnlyEd/next-right-now/tree/v2-mst-aptd-gcms-lcz-sty) (GraphQL + GraphCMS vendor)

See the [GraphCMS preset doc](https://unlyed.github.io/next-right-now/available-presets/v2-mst-aptd-gcms-lcz-sty)

**Comment by omeraplak** [comment]
@vitaliemiron Hi,
It has been a long time since we started next-boilerplate project. We are proud that it helped many frontend developers around the globe to speed up their frontend development cycles.

In time, we took valuable lessons from our experience and the community feedback:

- There are infinite number of frontend technologies and it's impossible to combine everything in a single boilerplate product.
- The project is hard to maintain with tons of external dependencies.
To tackle the complexity problem we started a new project from scratch. We call it "superplate" - the frontend boilerplate with superpowers.

It's built on top of a plugin architecture and allows you integrate your own tools and best practices with ease. It also includes more than 30 built-in plugins of your favorite tools.

superplate's default framework is Next.js, so you can start using it immediately instead of next-boilerplate. More framework targets are coming soon.

You may checkout the project from the [repo page](https://github.com/pankod/superplate) or [documentation](https://pankod.github.io/superplate/).
